"use client";

import type { IScannerControls } from "@zxing/browser";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { parseItemCode } from "@/lib/qr";

function cameraError(error: unknown): string {
  const name = error instanceof Error ? error.name : "";

  if (name === "NotAllowedError" || name === "SecurityError") {
    return "Camera access was denied. Allow camera access in your browser, or paste the item code below.";
  }

  if (name === "NotFoundError" || name === "OverconstrainedError") {
    return "No usable camera was found. Connect a camera, or paste the item code below.";
  }

  if (name === "NotReadableError" || name === "AbortError") {
    return "The camera could not start. Close other apps using it and try again, or paste the item code below.";
  }

  return "The camera could not read the code. Try again, or paste the item code below.";
}

export function QRScanner() {
  const router = useRouter();
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const controlsRef = useRef<IScannerControls | null>(null);
  const sessionRef = useRef(0);
  const initializingRef = useRef(false);
  const mountedRef = useRef(false);
  const [status, setStatus] = useState<"idle" | "starting" | "scanning">("idle");
  const [initializing, setInitializing] = useState(false);
  const [error, setError] = useState("");
  const [code, setCode] = useState("");

  // Invalidating the session also cancels pending imports, permission requests,
  // and decode initialization: any late stream/controls are immediately stopped.
  const releaseCamera = useCallback(() => {
    sessionRef.current += 1;
    controlsRef.current?.stop();
    controlsRef.current = null;
    streamRef.current?.getTracks().forEach((track) => track.stop());
    streamRef.current = null;

    if (videoRef.current) {
      videoRef.current.srcObject = null;
    }
  }, []);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      releaseCamera();
    };
  }, [releaseCamera]);

  function stopCamera() {
    releaseCamera();
    setStatus("idle");
  }

  function openItem(value: string) {
    const id = parseItemCode(value);
    stopCamera();

    if (!id) {
      setError("This is not a SupplyHub item code. Scan a label generated by this system, or enter its item UUID.");
      return;
    }

    setError("");
    router.push(`/inventory/${id}?movement=stock_out`);
  }

  async function startCamera() {
    // A permission prompt cannot be aborted. Do not overlap its initialization
    // with another session whose preview the old reader could later clear.
    if (initializingRef.current) return;
    releaseCamera();
    const session = sessionRef.current;
    const video = videoRef.current;
    setError("");

    if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) {
      setStatus("idle");
      setError("Camera scanning needs HTTPS and a supported browser. You can paste the item code below instead.");
      return;
    }

    if (!video) return;
    initializingRef.current = true;
    setInitializing(true);
    setStatus("starting");

    try {
      const { BrowserQRCodeReader } = await import("@zxing/browser");
      if (session !== sessionRef.current) return;

      const stream = await navigator.mediaDevices.getUserMedia({
        audio: false,
        video: { facingMode: { ideal: "environment" } },
      });

      if (session !== sessionRef.current) {
        stream.getTracks().forEach((track) => track.stop());
        return;
      }

      streamRef.current = stream;
      const reader = new BrowserQRCodeReader();
      const controls = await reader.decodeFromStream(stream, video, (result, scanError, scanControls) => {
        if (session !== sessionRef.current) {
          scanControls.stop();
          return;
        }

        if (result) {
          scanControls.stop();
          openItem(result.getText());
          return;
        }

        // Missing/incomplete QR frames are normal while the camera is aiming.
        const kind = scanError?.getKind?.();
        if (scanError && !["NotFoundException", "ChecksumException", "FormatException"].includes(kind ?? "")) {
          scanControls.stop();
          stopCamera();
          setError(cameraError(scanError));
        }
      });

      if (session !== sessionRef.current) {
        controls.stop();
        return;
      }

      controlsRef.current = controls;
      setStatus("scanning");
    } catch (cause) {
      if (session !== sessionRef.current) return;
      stopCamera();
      setError(cameraError(cause));
    } finally {
      initializingRef.current = false;
      if (mountedRef.current) setInitializing(false);
    }
  }

  function submitCode(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    openItem(code);
  }

  return (
    <section className="sys-panel" aria-labelledby="scanner-title">
      <h2 id="scanner-title">Scan an item label</h2>
      <p className="sys-muted">
        Scanning selects an item. Review its details and confirm the quantity on the next screen before any stock changes.
      </p>

      <video
        ref={videoRef}
        muted
        playsInline
        aria-label="QR scanner camera preview"
        style={{
          display: status === "idle" ? "none" : "block",
          width: "100%",
          maxWidth: 600,
          aspectRatio: "4 / 3",
          objectFit: "cover",
          borderRadius: 16,
          background: "#173659",
          marginBlock: 20,
        }}
      />

      <div className="sys-actions" style={{ marginBlock: 20 }}>
        {status === "idle" ? (
          <button type="button" className="sys-button" onClick={startCamera} disabled={initializing}>
            Start camera
          </button>
        ) : (
          <button type="button" className="sys-button sys-button-secondary" onClick={stopCamera}>
            Stop camera
          </button>
        )}
        <p className="sys-muted" role="status" aria-live="polite">
          {status === "starting" && "Waiting for camera access…"}
          {status === "scanning" && "Point the camera at a SupplyHub QR label."}
          {status === "idle" && (initializing
            ? "Camera stopped. Dismiss any open camera permission prompt to start again."
            : "Camera is off.")}
        </p>
      </div>

      {error && <p className="sys-error" role="alert" id="scanner-error">{error}</p>}

      <form className="sys-form" onSubmit={submitCode}>
        <label className="sys-field" htmlFor="item-code">
          <span>Or enter the item code</span>
          <input
            id="item-code"
            name="code"
            value={code}
            onChange={(event) => setCode(event.target.value)}
            placeholder="Item QR code or item UUID"
            autoComplete="off"
            autoCapitalize="none"
            spellCheck={false}
            maxLength={100}
            required
            aria-describedby={error ? "item-code-hint scanner-error" : "item-code-hint"}
          />
        </label>
        <p className="sys-muted" id="item-code-hint">
          Paste the value from a SupplyHub label. You can also <Link href="/inventory">find an item in inventory</Link>.
        </p>
        <button type="submit" className="sys-button">Review item</button>
      </form>
    </section>
  );
}
